POST http://localhost:3003/api/blogs
Content-Type: application/json

{
    "content": "Test Blog3",
	"title": "Uusi blogi",
	"author": "Niksu testi3",
	"url": "testi url",
	"likes": 9,
	"userId": "5f89754e6b92fd3830382f0f"
}
