POST http://localhost:3001/api/notes
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im5pa3N1IiwiaWQiOiI1Zjg5ZTkzMmMwMWZmYzFmOTQxMDNlYTQiLCJpYXQiOjE2MDI4NzM2NjN9.TZzgBzWodXz-cGT1m8FYLr_ZZjPXeOScpfYHuLgdd_E

{
    "content": "VS Code Rest client is pretty good",
    "important": false,
    "userId": "5f8730ee304e902498ba21e0"
}